### ISSUE TITLE
Let Customers Ask Chatbot for Shipping Price

### ISSUE THREAD

**Issue by a-garbar** [sap-tutorials/sap-conversational-ai#432]
Tutorials: https://developers.sap.com/tutorials/cai-bot-shipping-3-price-parcel.html
--------------------------
![typo-shipping-bot-tutorial](https://user-images.githubusercontent.com/94494737/142081148-e67f8225-4c33-4c9e-a2e8-5dc9ca282231.png)

**Comment by thecodester** [comment]
Fixed - https://github.com/SAPDocuments/sap-conversational-ai/commit/2ff40f3d5eaf9867647c9d69cd8986a6982daa31

Thanks.

**Comment by a-garbar** [comment]
https://people.sap.com/anna_garbar

**Comment by thecodester** [comment]
@a-garbar Do you mind that I mention you in an SAP blog as the first person to earn this badge?

**Comment by a-garbar** [comment]
Hi Daniel,

No, I don’t mind (didn’t know I am the first one 😊)
Looking forward to your blog!

Best regards,
Anna
