### ISSUE TITLE
Create a Chatbot that Lets Customers Track Packages

### ISSUE THREAD

**Issue by d023604** [sap-tutorials/sap-conversational-ai#436]
Tutorials: https://developers.sap.com/tutorials/cai-bot-shipping-1-track-bot.html
--------------------------

In Step 6 - Add Requirement to Skill: Item 4  _Next to If #parcel-number is missing, click New Replies, and then do the following:_
is missing the instruction to click Save. It is a very minor omission. 

Reset the memory:

   Click Update Conversation > Edit Memory.
   Under Unset Memory Field, add yes, then add another field to unset, no.
  **_Click Save_**

Click Back

**Comment by thecodester** [comment]
Updated https://github.com/sap-tutorials/sap-conversational-ai/commit/96ca6b1cae871ebebbb55d53615bbcb6355ba938

**Comment by d023604** [comment]
https://people.sap.com/andrew.barnard3
