### ISSUE TITLE
Add Webhook to Chatbot to Retrieve Tracking Info

### ISSUE THREAD

**Issue by d023604** [sap-tutorials/sap-conversational-ai#437]
Tutorials: https://developers.sap.com/tutorials/cai-bot-shipping-2-api.html
--------------------------

I think you could improve the tutorial by providing a link to the Python demo script referenced in Step 1: Set default endpoint for webhooks , Item 5.   _This endpoint contains a Python demo script that makes all kinds of API calls, including retrieving package information from UPS._

If the Python script is too complex, perhaps a cutdown version?

**Comment by thecodester** [comment]
Updated: https://github.com/sap-tutorials/sap-conversational-ai/commit/96ca6b1cae871ebebbb55d53615bbcb6355ba938
