### ISSUE TITLE
Question regarding images in tutorials

### ISSUE THREAD

**Issue by d023604** [sap-tutorials/sap-conversational-ai#438]
Good morning,
In several places in the sap-conversational-ai tutorials, the screen images vary from the current state of the user interface. Mostly the differences are very minor - in others the terminology has changed or the highlighted buttons have moved to another place. 

Would you like issues to be created for the more significant ones? and would it be helpful if the current screen image were provided?

Regards
Andrew Barnard

**Comment by thecodester** [comment]
We will have some complete review of all the tutorials at some point this year to update them as best we can. Thanlks for keeping an eye out, though :-)
